### ISSUE TITLE
H264 encoder crash

### ISSUE THREAD

**Issue by qiushics** [Intel-Media-SDK/MediaSDK#57]
H264 decoder, H265 encoder/decoder work well, only H264 encoder crash.

---

machine:
```
Linux ubuntu 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
intel i7 6700
```
---
below is the call stack:
```
Starting program: /opt/intel/mediasdk/samples/sample_encode h264 -nv12 -i a.yuv -o b.h264 -w 1920 -h 1080 -b 2000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff64f7700 (LWP 7792)]
[New Thread 0x7ffff5cf6700 (LWP 7793)]
[New Thread 0x7ffff54f5700 (LWP 7794)]
[New Thread 0x7ffff4cf4700 (LWP 7795)]
[New Thread 0x7ffff44f3700 (LWP 7796)]
[New Thread 0x7ffff3cf2700 (LWP 7797)]
[New Thread 0x7ffff34f1700 (LWP 7798)]
[New Thread 0x7ffff2cf0700 (LWP 7799)]
libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0

Thread 1 "sample_encode" received signal SIGSEGV, Segmentation fault.
0x00007ffff0cf6d33 in GmmLib::GmmResourceInfoCommon::Create (this=this@entry=0x7957d0, CreateParams=...)
    at /home/dev/code/intel/driver/gmmlib/Source/GmmLib/Resource/GmmResourceInfoCommon.cpp:96
96          GET_GMM_CLIENT_TYPE(pClientContext, ClientType);
(gdb) bt
#0  0x00007ffff0cf6d33 in GmmLib::GmmResourceInfoCommon::Create (this=this@entry=0x7957d0, CreateParams=...)
    at /home/dev/code/intel/driver/gmmlib/Source/GmmLib/Resource/GmmResourceInfoCommon.cpp:96
#1  0x00007ffff0cff315 in GmmLib::GmmClientContext::CreateResInfoObject (this=0x3100000004, pCreateParams=pCreateParams@entry=0x7fffffff25e0)
    at /home/dev/code/intel/driver/gmmlib/Source/GmmLib/GlobalInfo/GmmClientContext.cpp:379
#2  0x00007ffff0ce2acc in GraphicsResourceSpecific::Allocate (this=0x7956d0, osContextPtr=0x764380, params=...)
    at /home/dev/code/intel/driver/media-driver/media_driver/linux/common/os/mos_graphicsresource_specific.cpp:209
#3  0x00007ffff0ce508e in Mos_Specific_AllocateResource (pOsInterface=0x7614c0, pParams=0x7fffffff2900, pOsResource=0x7955f0)
    at /home/dev/code/intel/driver/media-driver/media_driver/linux/common/os/mos_os_specific.c:1649
#4  0x00007ffff0b66db1 in Heap::Allocate (this=this@entry=0x7955a0, heapSize=heapSize@entry=532480, keepLocked=<optimized out>)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/heap_manager/heap.cpp:89
#5  0x00007ffff0b6a069 in MemoryBlockManager::RegisterHeap (this=this@entry=0x766e30, heapId=<optimized out>, size=size@entry=532480)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/heap_manager/memory_block_manager.cpp:238
#6  0x00007ffff0b6732d in HeapManager::AllocateHeap (size=<optimized out>, this=0x766e28)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/heap_manager/heap_manager.cpp:192
#7  HeapManager::AcquireSpace (this=this@entry=0x766e28, params=..., blocks=std::vector of length 0, capacity 0, spaceNeeded=@0x7fffffff2a5c: 32767)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/heap_manager/heap_manager.cpp:48
#8  0x00007ffff0b71cca in XMHW_STATE_HEAP_INTERFACE::AssignSpaceInStateHeap (bZeroAssignedMem=<optimized out>, bStatic=<optimized out>,
    dwSpaceRequested=<optimized out>, pKernelState=<optimized out>, StateHeapType=<optimized out>, this=<optimized out>)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/hw/mhw_state_heap.c:1184
#9  Mhw_StateHeapInterface_AssignSpaceInStateHeap (pCommonStateHeapInterface=<optimized out>, StateHeapType=<optimized out>,
    pKernelState=<optimized out>, dwSpaceRequested=<optimized out>, bStatic=<optimized out>, bZeroAssignedMem=<optimized out>)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/hw/mhw_state_heap.c:146
#10 0x00007ffff0ad2aaa in CodechalHwInterface::MhwInitISH (stateHeapInterface=<optimized out>, kernelState=kernelState@entry=0x76ed60)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_hw.cpp:1202
#11 0x00007ffff0b1762d in CodechalEncodeAvcEnc::InitKernelStateMe (this=0x769360)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp:8108
#12 0x00007ffff0b2289c in CodechalEncodeAvcEnc::Initialize (this=0x769360, settings=<optimized out>)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp:1668
#13 0x00007ffff0b138ac in CodechalEncoderState::Allocate (this=0x769360, codecHalSettings=0x752310)
    at /home/dev/code/intel/driver/media-driver/media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp:483
#14 0x00007ffff0ca024c in DdiEncode_CreateContext (ctx=<optimized out>, config_id=<optimized out>, picture_width=1920,
    picture_height=<optimized out>, flag=<optimized out>, render_targets=0x6f6670, num_render_targets=4, context=0x742988)
    at /home/dev/code/intel/driver/media-driver/media_driver/linux/common/codec/ddi/media_libva_encoder.cpp:352
#15 0x00007ffff64fd262 in vaCreateContext (dpy=0x6cb060, config_id=1032, picture_width=1920, picture_height=1088, flag=flag@entry=1,
    render_targets=0x6f6670, num_render_targets=4, context=0x742988) at va.c:1175
#16 0x00007ffff6851fa7 in MfxHwH264Encode::VAAPIEncoder::CreateAccelerationService (this=0x73aa70, par=...)
    at /home/dev/code/intel/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp:1584
#17 0x00007ffff685011b in MfxHwH264Encode::VAAPIEncoder::Register (this=0x73aa70, response=..., type=842094158)
    at /home/dev/code/intel/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp:1900
#18 0x00007ffff67c3798 in MfxHwH264Encode::ImplementationAvc::Init (this=this@entry=0x723300, par=par@entry=0x6c3d10)
    at /home/dev/code/intel/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:947
#19 0x00007ffff67c4a39 in MFXHWVideoENCODEH264::Init (this=0x702780, par=0x6c3d10)
    at /home/dev/code/intel/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:193
#20 0x00007ffff673a319 in MFXVideoENCODE_Init (session=0x6c5028, par=0x6c3d10)
    at /home/dev/code/intel/MediaSDK/_studio/mfx_lib/shared/src/libmfxsw_encode.cpp:391
#21 0x000000000042ed91 in MFXVideoENCODE::Init (par=0x6c3d10, this=<optimized out>) at /home/dev/code/intel/MediaSDK/api/include/mfxvideo++.h:81
#22 CEncodingPipeline::ResetMFXComponents (this=0x6c3c80, pParams=0x7fffffffd4f0)
    at /home/dev/code/intel/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:1601
#23 0x00000000004352a6 in CEncodingPipeline::Init (this=0x6c3c80, pParams=0x7fffffffd4f0)
    at /home/dev/code/intel/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:1392
#24 0x0000000000418159 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/dev/code/intel/MediaSDK/samples/sample_encode/src/sample_encode.cpp:1173
```
---
test result:
```
python3.5 ted.py --gold
Intel(R) Media SDK Open Source TEst Driver
Copyright (c) Intel Corporation

Setting up test environment...
Disovering tests...
  h265e_func - 2 cases
  vpp_resize - 2 cases
  h264e_func_la - 18 cases
  vpp_denoise - 6 cases
  vpp_fourcc - 4 cases
  h264d_conf - 4 cases
  h264d_to_many - 1 cases
  h264e_func - 12 cases
  vpp_deinterlace - 8 cases
  h265d_conf - 4 cases

Collecting gold results for 10 tests...
  h265e_func
    0001 - ok
    0002 - ok
  vpp_resize
    0001 - ok
    0002 - ok
  h264e_func_la
    0001 - ok
    0002 - FAIL
    0003 - ok
    0004 - FAIL
    0005 - ok
    0006 - FAIL
    0007 - ok
    0008 - FAIL
    0009 - ok
    0010 - FAIL
    0011 - ok
    0012 - FAIL
    0013 - ok
    0014 - FAIL
    0015 - ok
    0016 - FAIL
    0017 - ok
    0018 - FAIL
  vpp_denoise
    0001 - ok
    0002 - ok
    0003 - ok
    0004 - ok
    0005 - ok
    0006 - ok
  vpp_fourcc
    0001 - ok
    0002 - ok
    0003 - ok
    0004 - ok
  h264d_conf
    0001 - FAIL
    0002 - FAIL
    0003 - FAIL
    0004 - FAIL
  h264d_to_many
    0001 - FAIL
  h264e_func
    0001 - ok
    0002 - FAIL
    0003 - ok
    0004 - FAIL
    0005 - ok
    0006 - FAIL
    0007 - ok
    0008 - FAIL
    0009 - ok
    0010 - FAIL
    0011 - ok
    0012 - FAIL
  vpp_deinterlace
    0001 - ok
    0002 - ok
    0003 - ok
    0004 - ok
    0005 - ok
    0006 - ok
    0007 - ok
    0008 - ok
  h265d_conf
    0001 - FAIL
    0002 - FAIL
    0003 - FAIL
    0004 - FAIL
```
37 of 61 cases passed

**Comment by adydychk** [comment]
@qiushics Thanks for the reporting. Can you provide more information about your compiler and environment?

**Comment by qiushics** [comment]
@adydychk Thanks for replay, it's gmmlib problem. Now fixed.
